#!/bin/bash
# Adds VITE_ prefixed environment variables required by the frontend
# Run this after dfx deploy backend

set -e

# Get backend canister ID
BACKEND_ID=$(dfx canister id backend 2>/dev/null)
if [ -z "$BACKEND_ID" ]; then
    echo "Error: Backend canister not found. Run 'dfx deploy backend' first."
    exit 1
fi

# Determine network
NETWORK=${DFX_NETWORK:-local}
if dfx canister id backend --network ic &>/dev/null; then
    NETWORK="ic"
fi

# Internet Identity canister ID (same on all networks)
II_ID="rdmx6-jaaaa-aaaaa-aaadq-cai"

# Remove old VITE_ variables if they exist
if [ -f .env ]; then
    grep -v "^VITE_" .env > .env.tmp 2>/dev/null || true
    mv .env.tmp .env
fi

# Append VITE_ variables
cat >> .env << EOF

# Vite environment variables (auto-generated by setup-env.sh)
VITE_DFX_NETWORK='${NETWORK}'
VITE_CANISTER_ID_BACKEND='${BACKEND_ID}'
VITE_CANISTER_ID_INTERNET_IDENTITY='${II_ID}'
EOF

echo "✓ Added VITE_ environment variables to .env"
echo "  VITE_DFX_NETWORK='${NETWORK}'"
echo "  VITE_CANISTER_ID_BACKEND='${BACKEND_ID}'"
echo "  VITE_CANISTER_ID_INTERNET_IDENTITY='${II_ID}'"
